export const UPDATE_TRANSACTION_LIST = 'TRANSACTION/UPDATE_LIST';
export const UPDATE_PENDING_TRANSACTION_LIST = 'TRANSACTION/UPDATE_PENDING_TRANSFERS';
export const UPDATE_TOKEN_LIST = 'TOKEN/UPDATE_LIST';
export const UPDATE_SELECTED_TOKEN = 'TOKEN/UPDATE_SELECTED';
export const LOCK_APP = 'APP/LOCK_APP';
export const UPDATE_TRANSACTION_HISTORY = 'UPDATE_TRANSACTION_HISTORY';
export const UPDATE_TRANSACTION_PAGE = 'UPDATE_TRANSACTION_PAGE';
export const UPDATE_LOAD_MORE = 'UPDATE_LOAD_MORE';
