export const APPSTATE_CHANGE_PAGE_STATUS = 'APPSTATE/CHANGE_PAGE_STATUS';
export const APPSTATE_IS_LOADING = 'APPSTATE/IS_LOADING';
export const APPSTATE_IS_APP_ONBOARDED = 'APPSTATE/IS_APP_ONBOARDED';
export const APPSTATE_MANIFEST = 'APPSTATE/APP_MANIFEST';
export const APPSTATE_UPDATE_BACKUP_PAGE = 'APPSTATE/UPDATE_BACKUP_PAGE';
export const APPSTATE_LANGUAGE = 'APPSTATE/LANGUAGE';
export const APPSTATE_SHOW_VALIDATE_PASSWORD = 'APPSTATE/SHOW_VALIDATE_PASSWORD';
