export const UNLOCK_CRUST_SUCCESS = 'ACCOUNT/UNLOCK_CRUST_SUCCESS';
export const UNLOCK_CRUST_ERROR = 'ACCOUNT/UNLOCK_CRUST_ERROR';
export const UNLOCK_CRUST_SUCCESS_FALSE = 'ACCOUNT/UNLOCK_CRUST_SUCCESS_FALSE';
